package config

import (
	"strings"
	"testing"
)

func TestParseStrictAndLiteral(t *testing.T) {
	tests := []struct{ name, yaml, want string }{
		{"unknown top-level", "reposistory: {}", "field reposistory not found"},
		{"unknown nested", "repository:\n  has_wikii: true", "field has_wikii not found"},
		{"multiple documents", "repository:\n  has_wiki: true\n---\nrepository: {}", "multiple YAML documents"},
		{"empty", "---\n", "at least one managed section"},
		{"json", `{"repository":{"has_wiki":true}}`, "JSON configuration is not supported"},
		{"bad permission", "collaborators:\n  octocat:\n    permission: owner", "not pull, triage"},
		{"bad actions policy", "actions:\n  allowed_actions: sometimes", "must be all, local_only, or selected"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			_, err := Parse([]byte(tt.yaml))
			if err == nil || !strings.Contains(err.Error(), tt.want) {
				t.Fatalf("Parse() error = %v, want containing %q", err, tt.want)
			}
		})
	}
}

func TestParsePresenceSemantics(t *testing.T) {
	c, err := Parse([]byte("repository:\n  has_wiki: false\ncollaborators: {}\n"))
	if err != nil {
		t.Fatal(err)
	}
	if c.Repository == nil || c.Repository.HasWiki == nil || *c.Repository.HasWiki {
		t.Fatalf("present false value was not preserved: %#v", c.Repository)
	}
	if c.Repository.HasIssues != nil {
		t.Fatal("omitted scalar must be unmanaged")
	}
	if c.Collaborators == nil || len(*c.Collaborators) != 0 {
		t.Fatal("present empty collection must be authoritative")
	}
	if c.Teams != nil {
		t.Fatal("omitted collection must be unmanaged")
	}
}

func TestRulesetParametersAreStrict(t *testing.T) {
	_, err := Parse([]byte("rulesets:\n  main:\n    enforcement: active\n    rules:\n      - type: pull_request\n        parameters:\n          required_approving_reviews_count: 2\n"))
	if err == nil || !strings.Contains(err.Error(), "required_approving_reviews_count not found") {
		t.Fatalf("expected nested unknown-key error, got %v", err)
	}
}

func TestIntentionallyUnmanagedSettingsHaveActionableErrors(t *testing.T) {
	for yaml, want := range map[string]string{"repository:\n  visibility: private": "visibility changes are high risk", "repository:\n  archived: true": "archive changes are high risk", "secrets:\n  TOKEN: value": "secrets are intentionally unmanaged"} {
		_, err := Parse([]byte(yaml))
		if err == nil || !strings.Contains(err.Error(), want) {
			t.Errorf("Parse(%q) error=%v, want %q", yaml, err, want)
		}
	}
}

func TestRuleParametersMustMatchRuleType(t *testing.T) {
	_, err := Parse([]byte("rulesets:\n  main:\n    enforcement: active\n    rules:\n      - type: deletion\n        parameters:\n          pattern: nope\n"))
	if err == nil || !strings.Contains(err.Error(), "does not accept parameters") {
		t.Fatalf("error = %v", err)
	}
}

func TestMarshalRoundTrip(t *testing.T) {
	c, err := Parse([]byte("repository:\n  topics: [go, github]\nteams:\n  platform:\n    permission: maintain\n"))
	if err != nil {
		t.Fatal(err)
	}
	b, err := Marshal(c)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(string(b), "# Generated by ghrepocfg") {
		t.Fatalf("missing header: %s", b)
	}
	if _, err := Parse(b); err != nil {
		t.Fatalf("generated YAML did not round trip: %v\n%s", err, b)
	}
}
